// <auto-generated />
using System;
using Magic.curso.net.modelos.Dtos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Magic.curso.net.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Magic.curso.net.modelos.Villa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Amenidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fechacreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetrosCuadrados")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ocupante")
                        .HasColumnType("int");

                    b.Property<double>("Tarifa")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("villas");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Amenidad = "",
                            Detalle = "detalle de la villa ",
                            FechaActualizacion = new DateTime(2024, 5, 23, 21, 0, 26, 659, DateTimeKind.Local).AddTicks(1182),
                            Fechacreacion = new DateTime(2024, 5, 23, 21, 0, 26, 659, DateTimeKind.Local).AddTicks(1166),
                            ImagenUrl = "",
                            MetrosCuadrados = 50,
                            Nombre = "villa real",
                            Ocupante = 5,
                            Tarifa = 200.0
                        },
                        new
                        {
                            ID = 2,
                            Amenidad = "",
                            Detalle = "detalle de la villa con vista a la piscina",
                            FechaActualizacion = new DateTime(2024, 5, 23, 21, 0, 26, 659, DateTimeKind.Local).AddTicks(1187),
                            Fechacreacion = new DateTime(2024, 5, 23, 21, 0, 26, 659, DateTimeKind.Local).AddTicks(1186),
                            ImagenUrl = "",
                            MetrosCuadrados = 40,
                            Nombre = "villa premiun vista a la piscina",
                            Ocupante = 4,
                            Tarifa = 250.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
